# Generated by Django 5.2.5 on 2025-09-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prouduct_image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
    ]
